[tool.poetry]
authors = [
    "Parker Hasenkamp <hasenkap@student.psdr3.org>",
]
description = "A game."
name = "textbasedgame"
packages = [
    { include = "textbasedgame", from = "src" },
]
version = "0.1.0"

[tool.poetry.dependencies]
Pillow   = "^9.5.0"
colorama = "^0.4.6"
numpy    = "^1.24.3"
python   = ">=3.10.0,<3.11"
readchar = "^4.0.5"

[tool.poetry.dev-dependencies]
debugpy = "^1.6.2"
replit-python-lsp-server = { extras = [
    "pyflakes",
    "rope",
    "yapf",
], version = "^1.5.9" }

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires      = ["poetry-core>=1.0.0"]
